### PR TITLE
Feature/auto translate title notes

### PR DESCRIPTION
**Pull request by mpolidori**
Steps to use autotranslations:

Clone [`ckanext-scheming`](https://github.com/ckan/ckanext-scheming) (working on master), enable in `plugins` with `scheming_datasets` and add `.env` variables:

```
CKAN___SCHEMING__DATASET_SCHEMAS=ckanext.portalopendatadk.schema:oddk_schema.yaml
CKAN___SCHEMING__PRESETS=ckanext.scheming:presets.json ckanext.fluent:presets.json
```
Clone [`ckanext-fluent`](https://github.com/ckan/ckanext-fluent) (working on master) and enable in `plugins` with `fluent`.

Clone [`ckanext-translate`](https://github.com/datopian/ckanext-translate) (v0.3.0) and add credentials to the `.env`:

```
CKANEXT__TRANSLATE__IBM_URL=ACCOUNT_URL
CKANEXT__TRANSLATE__IBM_KEY=ACCOUNT_KEY
```

### CODE REVIEW

**Comment by mpolidori** [comment]
Everything is working fine except for markdown after translation. I'm looking into this.

API output:

Screenshot(200)

Dataset form:

Screenshot(204)

Dataset page in Danish:

Screenshot(201)

Dataset page in English:

Screenshot(202)

Dataset page in French:

Screenshot(203)

**Comment by anuveyatsu** [comment]
@mpolidori so are we now handling markdown?

**Comment by mpolidori** [comment]
@anuveyatsu Yeah. Osahon pinged me to ask about it and I told him that I can get it working with an additional package `html2text` (aside from `markdown` which is included in the CKAN requirements) and he had no objections. I've tested with and without markdown in the description and it's working fine. We can discuss it further if you have any concerns though.

**Comment by anuveyatsu** [comment]
@mpolidori I'm fine with it in general. My only concern is that it might add complexity in the future when we will be doing CKAN upgrade. But I think we should go ahead and merge this which I'm going to do now.

**Review by anuveyatsu — APPROVED** [review]
Thanks @mpolidori

**Pull request merged**
