### PR TITLE
Checkbox

### PR DESCRIPTION
**Pull request by geoffrey1330**

### CODE REVIEW

**Review by mpolidori — CHANGES_REQUESTED** [review]
ODDK uses https://github.com/ckan/ckanext-scheming. When the scheming extension is enabled, changes to `package_metadata_fields.html` aren't reflected in the UI. You will need to add your checkbox in this file as well https://github.com/datopian/ckanext-portalopendatadk/blob/checkbox/ckanext/portalopendatadk/schema/oddk_schema.yaml#L63

And a few additional changes that are needed:

1. The value of the checkbox needs to be saved/persistent
2. `package_search` API output needs to include the current value: `data_directory: true` or `data_directory: false`
3. In the dataset form, the checkbox should be disabled or read-only for any user other than sysadmins

**Comment by mpolidori** [comment]
@geoffrey1330 Oh, one more thing. You need to make sure the translation for "Data directory" (translation: "Datavejviser") is added to https://github.com/datopian/ckanext-portalopendatadk/blob/master/ckanext/portalopendatadk/i18n/da_DK/LC_MESSAGES/ckanext-portalopendatadk.po

**Comment by geoffrey1330** [comment]
>

**Comment by geoffrey1330** [comment]
> 

Alright

**Review by mpolidori — APPROVED** [review]
Looks good to me!

**Pull request merged**
